# Generated by Django 3.2.23 on 2023-12-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20231212_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
